# This workflow will do a clean build of a docker image and publish said image to a registry.
name: Docker Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        
    - name: Build docker image
      run: docker build --tag journal-api .

    - name: Publish image
      uses: raccoondev/push-docker-gcr
      with:
        gcr_host: eu.gcr.io
        image_name: journal-api
        image_tag: latest
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      

      
